# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, cereal, optparseApplicative, STL, text }:

cabal.mkDerivation (self: {
  pname = "stl-examples";
  version = "0.2";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ attoparsec cereal optparseApplicative STL text ];
  meta = {
    homepage = "http://github.com/bergey/STL";
    description = "usage examples for the STL library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
